AnalysisError: Rename to AnalysisDiagnostic. EquatableHashSet: Add efficient way to combine methods of different network objects while respecting inheritance and methods that may have different parameters but the same name. RegisterObjectsGenerator: Successfully fetches all network methods including inherited ones. The final method list is how the methods would look from the perspective of the most derived class.